=== rodriSM3012/LMSGI/Tema3/xml/2/index.dtd
<!ELEMENT libreria (libros,revistas)>
<!ELEMENT libros (libro+)>
<!ELEMENT libro (titulo,autor,paginas?,editorial,precio)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT paginas (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda NMTOKEN #IMPLIED>
<!ELEMENT revistas (revista)>
<!ELEMENT revista (#PCDATA)>

=== rodriSM3012/LMSGI/Tema3/xml/2/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria SYSTEM "index.dtd">
<libreria>
    <libros>
        <libro>
            <titulo>La Biblia</titulo>
            <autor>Varios</autor>
            <paginas>3254</paginas>
            <editorial>Libros La Fe</editorial>
            <precio moneda="euros">35</precio>
        </libro>
        <libro>
            <titulo>Harry Potter</titulo>
            <autor>La Innombrable</autor>
            <editorial>Salamandra</editorial>
            <precio>50</precio>
        </libro>
    </libros>
    <revistas>
        <revista>patata</revista>
    </revistas>
</libreria>
