=== rodriSM3012/LMSGI/Tema4/4/index.dtd
<!ELEMENT tiendaAnimales (terrestres, acuaticos)>
<!ELEMENT terrestres (animales+)>
<!ELEMENT acuaticos (animalesAcuaticos+)>
<!ELEMENT animales (especie, origen, descripcion, precio, sexo?, color+, pack*, (transporte | seguro | descuento))>
<!ELEMENT especie (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ATTLIST origen continente CDATA #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio moneda CDATA #IMPLIED>

<!ELEMENT sexo (#PCDATA)> <!-- opcional -->
<!ELEMENT color (#PCDATA)> <!-- 1 o mas -->
<!ELEMENT pack (#PCDATA)> <!-- 0,1 o mas de 1-->

<!-- solo puede haber 1 de los siguientes 3-->
<!ELEMENT transporte (#PCDATA)>
<!ELEMENT seguro (#PCDATA)>
<!ELEMENT descuento (#PCDATA)>
<!ATTLIST descuento importe CDATA #REQUIRED>

<!ELEMENT animalesAcuaticos (especie, origen, descripcion, precio, sexo?, color+, pack*, (transporte | seguro | descuento), medio)>
<!ELEMENT medio EMPTY>
<!ATTLIST medio elemento (salada) #REQUIRED>

=== rodriSM3012/LMSGI/Tema4/4/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tiendaAnimales SYSTEM "index.dtd">
<tiendaAnimales>
    <terrestres>
        <animales>
            <especie></especie>
            <origen continente=""></origen>
            <descripcion></descripcion>
            <precio></precio>
            <sexo></sexo>
            <color></color>
            <pack></pack>
            <transporte></transporte>
            <!-- <seguro></seguro> -->
            <!-- <descuento></descuento> -->
        </animales>
        <animales>
            <especie></especie>
            <origen continente=""></origen>
            <descripcion></descripcion>
            <precio moneda=""></precio>
            <color></color>
            <color></color>
            <!-- <transporte></transporte> -->
            <seguro></seguro>
            <!-- <descuento></descuento> -->
        </animales>
        <animales>
            <especie></especie>
            <origen continente=""></origen>
            <descripcion></descripcion>
            <precio></precio>
            <color></color>
            <color></color>
            <color></color>
            <!-- <transporte></transporte> -->
            <!-- <seguro></seguro> -->
            <descuento importe=""></descuento>
        </animales>
    </terrestres>
    <acuaticos>
        <animalesAcuaticos>
        <especie></especie>
            <origen continente=""></origen>
            <descripcion></descripcion>
            <precio></precio>
            <sexo></sexo>
            <color></color>
            <pack></pack>
            <transporte></transporte>
            <!-- <seguro></seguro> -->
            <!-- <descuento></descuento> -->
            <medio elemento="salada"></medio>
        </animalesAcuaticos>
    </acuaticos>
</tiendaAnimales>
